#! /bin/csh -f
# Written by Furey.
# With additions from Tony.

# Set the port number.
set port = 8080
if ( "$1" != "" ) set port="$1"

# set up
cd ../reports
if [ -f shutdown.txt ]; then rm -f shutdown.txt; fi

cd../area

# allow cores
ulimit -c 50000
# stack limit
ulimit -s 1500

renice +5 -p $$

# loop indefinately
while :
do

# Change to area directory.
# autokill 60 >> ~/area/autokill.txt &
cd ../area

# Set limits.
nohup
nice
limit stack 1024k
if ( -e shutdown.txt ) rm -f shutdown.txt

while ( 1 )
    # If you want to have logs in a different directory,
    #   change the 'set logfile' line to reflect the directory name.
    set index = 1000
    while ( 1 )
	set logfile = ../log/$index.log
	if ( ! -e $logfile ) break
	@ index++
    end

    # Run merc.
    ../src/merc $port >&! $logfile

    # Restart, giving old connections a chance to die.
    if ( -e shutdown.txt ) then
	rm -f shutdown.txt
	exit 0
    fi


cd ../area
    # sleep, so if we fail on boot we don't get massive looping
    sleep 10
done
