#! /bin/csh -f
# Written by Furey.
# With additions from Tony.

# Set the port number.
set port = 9090
if ( "$1" != "" ) set port="$1"

# Change to area directory.
# autokill 60 >> ~/area/autokill.txt &
cd ../area

# Set limits.
nohup
renice +5 -p $$
#allow cores
#ulimit -c 50000
#limit stack 1500k
#ulimit -s 1500
# loop indefinately
while :
do

if ( -e shutdown.txt ) rm -f shutdown.txt

while ( 1 )
    # If you want to have logs in a different directory,
    #   change the 'set logfile' line to reflect the directory name.
    set index = 1000
    while ( 1 )
	set logfile = ../log/$index.log
	if ( ! -e $logfile ) break
	@ index++
    end

    # Run merc.
    ../src/merc $port >&! $logfile

    # Restart, giving old connections a chance to die.
    if ( -e shutdown.txt ) then
	rm -f shutdown.txt
	exit 0
  fi

cd ../area
  
  # sleep, so if we fail on boot we don't get massive looping
  sleep 10
done
